---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse

- name : vector-role
  src: git@github.com:Frozzz54/vector-role.git
  scm: git
  version: "1.0.0"
  
- name : lighthouse-role
src: git@github.com:Frozzz54/lighthouse-role.git
scm: git
version: "1.0.0"