---
version: '3.6'

services: 
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    env_file: ./.env
    enviroment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes: 
      - ./postgres:/var/lib/postgresql/data:Z
      - ./backup:/backup
